name: Static check my answers
on:
  pull_request:
    paths:
      - playground/**
      - .github/workflows/static-check.yaml
  push:
    paths:
      - playground/**
      - .github/workflows/static-check.yaml
    branches:
      - main

jobs:
  static-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json
          cache: pnpm

      - name: install dependencies
        run: pnpm ci

      - name: typecheck
        run: pnpm typechk

      - name: lint  # ここでフォーマットチェックも実行される
        run: pnpm run lint
